"""
this script is to auto simulate the baseline fmu usinig inputs generated by MPC

Author: Yangyang Fu, Guowen Li
Email: yangyang.fu@tamu.edu, guowenli@tamu.edu
Revisions:
    2/11/2022
"""

# load testbed
from pyfmi import load_fmu
# import others
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import sys
import os
import json

### Load FMU
## ============================================================
####  Define FMU model path
### ======================================
# MODELICAPATH = os.getenv('MODELICAPATH')
# MODELICAPATH = MODELICAPATH.split(';')[0]
# LIBRARYPATH = os.path.join(MODELICAPATH, 'modelica-template', 'dymola')
# print(MODELICAPATH, LIBRARYPATH)

#hvac = load_fmu(os.path.join(LIBRARYPATH,"wrapped_fixed.fmu"))
#hvac = load_fmu("C:/Users/guowenli/Desktop/Github/modelica-fault-library/modelica-template/dymola/wrapped_fixed_modified_si2.fmu")
hvac = load_fmu("VirtualTestbed_NISTChillerTestbed_DemandFlexibilityInvestigation_FakeSystem_SystemForMPC_02bInputs_0RealtoBool.fmu")

## ===========================================================
# define measurements for the experiments
measurement_names = ['time',
                     'TOut.y',
                     'weaBus.TWetBul',
                     'weaBus.relHum',
                     'bChi.y',
                     'bIce.y',
                     'occSch.occupied',
                     'modCon.y',
                     'iceTan.SOC',
                     'chi.TSet',
                     'iceTan.TOutSet',
                     'TCHWSup.T',
                     'TCHWRetCoi.T',
                     'priPum.m_flow',
                     'secPum.m_flow',
                     'senRelPre.p_rel',
                     'conAHU.TSupSet',
                     'conAHU.TSup',
                     'senSupFlo.V_flow',
                     'conVAVCor.damVal.VDisSet_flow',
                     'VSupCor_flow.V_flow',
                     'conVAVSou.damVal.VDisSet_flow',
                     'VSupSou_flow.V_flow',
                     'conVAVEas.damVal.VDisSet_flow',
                     'VSupEas_flow.V_flow',
                     'conVAVNor.damVal.VDisSet_flow',
                     'VSupNor_flow.V_flow',
                     'conVAVWes.damVal.VDisSet_flow',
                     'VSupWes_flow.V_flow',
                     'conAHU.TZonCooSet',
                     'conAHU.TZonHeaSet',
                     'conVAVCor.TZon',
                     'conVAVSou.TZon',
                     'conVAVEas.TZon',
                     'conVAVNor.TZon',
                     'conVAVWes.TZon',
                     'ave.y',
                     'chi.P',
                     'priPum.P',
                     'secPum.P',
                     'fanSup.P'
                     ]
# fmu settings
options = hvac.simulate_options()
options['ncp'] = 50
options['initialize'] = True 
options['result_handling'] = 'memory'
options['filter'] = measurement_names

PH=2
# load mpc results from mpc experiment
with open('C:/Users/guowenli/Desktop/Github/nist-chiller-modelica/mpc/differentiable_neural_network/3_mpc/results/mpc_results_PH'+str(PH)+'.json','r') as f: 
    mpc_results = json.load(f)
# with open('C:/Users/guowenli/Desktop/DOE_CYDERS/AMPC/adaptive_cases_compensator/west_zone/mpc_results_attackWest_noCompensator_03302023.json','r') as f: 
#     mpc_results = json.load(f)

u_opt = mpc_results['u_opt']
t_opt = mpc_results['t_opt']
TCor_pred = np.array(mpc_results['Tz_core_pred_opt']) # deg C
TEas_pred = np.array(mpc_results['Tz_east_pred_opt'])
TNor_pred = np.array(mpc_results['Tz_north_pred_opt'])
TSou_pred = np.array(mpc_results['Tz_south_pred_opt'])
TWes_pred = np.array(mpc_results['Tz_west_pred_opt'])
Power_pred = mpc_results['P_pred_opt']

### Experiment setup
## ============================================================
ndays = 1
t_start = 212*24*3600+3*24*3600.  # simulation start time: 207*24*3600; August 1st day 212; issue day: 218
t_period = ndays*24*3600.
t_end = t_start + t_period  # simulation end time

dt = 4*15*60. # Timestep (seconds)

# inputs = ['oveOnChiPla_u', 'oveOnChiPla_activate', 'conAHU_supFan_oveOnSupFan_u', 'conAHU_supFan_oveOnSupFan_activate',
#           'oveTChiWatSupSet_u', 'oveTChiWatSupSet_activate', 'oveTConWatSupSet_u', 'oveTConWatSupSet_activate',
#           'conAHU_oveTSupAir_u', 'conAHU_oveTSupAir_activate', 'conVAVCor_damVal_oveVDisSet_u', 'conVAVCor_damVal_oveVDisSet_activate',
#           'conVAVEas_damVal_oveVDisSet_u', 'conVAVEas_damVal_oveVDisSet_activate', 'conVAVNor_damVal_oveVDisSet_u', 'conVAVNor_damVal_oveVDisSet_activate',
#           'conVAVSou_damVal_oveVDisSet_u', 'conVAVSou_damVal_oveVDisSet_activate', 'conVAVWes_damVal_oveVDisSet_u', 'conVAVWes_damVal_oveVDisSet_activate']

# #input_control=[bcp, bahu, Tchw, Tcw, Tsa, Vcore, Veast, Vnorth, Vsouth, Vwest, \epsilon]
# # separate control inputs and their activation flag for future use
# input_control = []
# input_control_activate = []
# for name in inputs:
#     if name.endswith('_activate'):
#         input_control_activate.append(name)
#     else:
#         input_control.append(name)
input_control = ['bc', 'bi']
#### Simulate the virtual testbed (VAV system) through fmu
res_mpc = []
for i in range(len(t_opt)):
    ts = t_opt[i]
    te = ts + dt
    ut = u_opt[i]
    # for activate in input_control_activate:
    #     hvac.set(activate, 1.)
    for j, u in zip(range(len(input_control)),input_control):
        hvac.set(u, ut[j])

    res = hvac.simulate(start_time = ts, final_time = te, options=options)
    res_mpc.append(res)

    # update fmu settings
    options['initialize'] = False

# organize results based on variable names and save into a dictionary
results = {}
for name in measurement_names:
    measurement = []
    for res in res_mpc:
        measurement += list(res[name])
    results[name] = np.array(measurement)

## Calculate metrics
results_pd = pd.DataFrame(results, index=results['time'])
# interpolate as time-series


def interpolate_dataframe(df, new_index):
    """Interpolate a dataframe along its index based on a new index
    """
    df_out = pd.DataFrame(index=new_index)
    df_out.index.name = df.index.name

    for col_name, col in df.items():
        df_out[col_name] = np.interp(new_index, df.index, col)
    return df_out


time_inp = np.arange(t_start, t_end+1, 60)  # every 60 seconds
results_60 = interpolate_dataframe(results_pd, time_inp)
results_900 = results_60.groupby(
    results_60.index//900).mean()  # every 15 minutes
#results_900.to_csv('results_900.csv')
#print(results_900['time'])
time_900 = np.arange(t_start, t_end+1, 900.)  # every 900 seconds

Power_tot=np.array([results_900['chi.P'],\
                    results_900['priPum.P'],\
                    results_900['secPum.P'],\
                    results_900['fanSup.P']]).sum(axis=0)

## plots
# time index for simulation data from fmu
time_xticks = np.arange(time_900[0], time_900[-1]+1., 4*3600.)
time_xticklabels = np.arange(0, 24*ndays+1, 4)

# plot 1 - chiller details
plt.figure(figsize=(12, 14))
# plt.subplot(711)
# plt.plot(time_900, results_900['mod.oveOnChiPla.y'], 'k-', label='Chiller')
# #plt.plot(time_900, results_900['mod.oveRelHumOutAir.y'], 'b', label='Relative humidity')
# plt.xticks(time_xticks,[])
# plt.ylabel('On')
# for i in range(ndays):
#     if i == 0:
#         plt.axvspan(t_start+7*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
#     else:
#         plt.axvspan(t_start+(7+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
# plt.legend(loc='upper left')

plt.subplot(611)
#plt.plot(time_900, results_900['mod.eleChi.y'], 'k-', label="Chiller")
#plt.plot(time_900, results['mod.eleCHWP.y'], label="CHWP")
#plt.plot(time_900, results['mod.eleCT.y'], label='Cooling Tower')
#plt.plot(time_900, results['mod.eleCWP.y'], label='CWP')
#plt.plot(time_900, results['mod.eleSupFan.y'], label='Supply Fan')
plt.plot(time_900, Power_tot, 'k-', label="total power")
plt.plot(t_opt, Power_pred, 'k:', label='Predicted')
plt.xticks(time_xticks,[])
plt.ylabel('Power [W]')
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.subplot(612)
plt.plot(time_900, results_900['weaBus.relHum'], 'k', label='Relative humidity')
plt.xticks(time_xticks,[])
plt.ylabel('Relative humidity')
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.subplot(613)
plt.plot(time_900, np.array(results_900['TOut.y'])-273.15, 'k-',label='outdoor air dry bulb temp')
plt.plot(time_900, np.array(results_900['weaBus.TWetBul'])-273.15, 'k--',label='outdoor air wet bulb temp')
plt.ylabel('Outdoor air \n temperature [C]')
plt.xticks(time_xticks, [])
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.subplot(614)
plt.plot(time_900, np.array(results_900['bChi.y']), 'k-',label='Chiller ON/OFF')
plt.ylabel('ON/OFF')
plt.xticks(time_xticks, [])
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.subplot(615)
plt.plot(time_900, np.array(results_900['bIce.y']), 'k-',label='TES ON/OFF')
plt.ylabel('ON/OFF')
plt.xticks(time_xticks, [])
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.subplot(616)
plt.plot(time_900, np.array(results_900['iceTan.SOC']), 'k-',label='State-of-Charge')
plt.ylabel('SOC')
plt.xlabel('Time [h]')
plt.xticks(time_xticks, time_xticklabels)
for i in range(ndays):
    if i == 0:
        plt.axvspan(t_start+6*3600, t_start+19*3600, alpha=0.1, color='grey', label='Occupied')
    else:
        plt.axvspan(t_start+(6+24*i)*3600, t_start+(19+24*i)*3600, alpha=0.1, color='grey', label=None)
plt.legend(loc='upper left')

plt.savefig('./results/chiller_PH'+str(PH)+'.png')

# plot 2
# upper bound and lower bound of zone temperature
Tupper, Tlower = [30.]*len(time_900), [18.]*len(time_900)
for i in range(len(time_900)):
    if int(time_900[i]%(24*3600)/3600) >= 6 and int(time_900[i]%(24*3600)/3600) < 19:
        Tupper[i] = 25
        Tlower[i] = 20
    else:
        Tupper[i] = 30
        Tlower[i] = 18 

plt.figure(figsize=(12,10))
plt.subplot(521)
# plot upper_lim of the room temperature
plt.plot(time_900, Tupper, 'k--', lw=0.5, label='Bounds')
# plot lower_limit of the room temperature
plt.plot(time_900, Tlower, 'k--', lw=0.5)
plt.plot(time_900, results_900['conVAVCor.TZon']-273.15, 'b-', label='Measured')
plt.plot(t_opt, TCor_pred, 'b:', label='Predicted')
plt.ylabel('Core Zone')
plt.xticks(time_xticks, [])
plt.yticks()
plt.title('Temperature [C]')
plt.legend(loc=4,fontsize=10)

plt.subplot(522)
plt.plot(time_900, results_900['VSupCor_flow.V_flow'], 'b-',label='Measured')
plt.plot(time_900, results_900['conVAVCor.damVal.VDisSet_flow'], 'b:', label='Setpoint')
plt.xticks(time_xticks, [])
plt.yticks()
plt.ylim(0,4.5,0.5)
plt.title('Flowrate [m3/s]')
plt.legend(loc=4)

plt.subplot(523)
# plot upper_lim of the room temperature
plt.plot(time_900, Tupper, 'k--', lw=0.5, label='Bounds')
# plot lower_limit of the room temperature
plt.plot(time_900, Tlower, 'k--', lw=0.5)
plt.plot(time_900, results_900['conVAVEas.TZon']-273.15, 'b-',label='Measurement')
plt.plot(t_opt, TEas_pred, 'b:', label='Prediction')
plt.ylabel('East Zone')
plt.xticks(time_xticks, [])
plt.yticks()

plt.subplot(524)
plt.plot(time_900, results_900['VSupEas_flow.V_flow'], 'b-', label='Measured')
plt.plot(time_900, results_900['conVAVEas.damVal.VDisSet_flow'], 'b:',label='Setpoint')
plt.xticks(time_xticks, [])
plt.yticks()
plt.ylim(0,1,1)

plt.subplot(525)
# plot upper_lim of the room temperature
plt.plot(time_900, Tupper, 'k--', lw=0.5, label='Bounds')
# plot lower_limit of the room temperature
plt.plot(time_900, Tlower, 'k--', lw=0.5)
plt.plot(time_900, results_900['conVAVNor.TZon']-273.15, 'b-',label='Measurement')
plt.plot(t_opt, TNor_pred, 'b:', label='Prediction')
plt.ylabel('North Zone')
plt.xticks(time_xticks, [])
plt.yticks()

plt.subplot(526)
plt.plot(time_900, results_900['VSupNor_flow.V_flow'], 'b-', label='Measured')
plt.plot(time_900, results_900['conVAVNor.damVal.VDisSet_flow'], 'b:', label='Setpoint')
plt.xticks(time_xticks, [])
plt.yticks()
plt.ylim(0,1,1)

plt.subplot(527)
# plot upper_lim of the room temperature
plt.plot(time_900, Tupper, 'k--', lw=0.5, label='Bounds')
# plot lower_limit of the room temperature
plt.plot(time_900, Tlower, 'k--', lw=0.5)
plt.plot(time_900, results_900['conVAVSou.TZon']-273.15, 'b-',label='Measurement')
plt.plot(t_opt, TSou_pred, 'b:',label='Prediction')
plt.ylabel('South Zone')
plt.xticks(time_xticks, [])
plt.yticks()

plt.subplot(528)
plt.plot(time_900, results_900['VSupSou_flow.V_flow'],'b-',label='Measured')
plt.plot(time_900, results_900['conVAVSou.damVal.VDisSet_flow'], 'b:',label='Setpoint')
plt.xticks(time_xticks, [])
plt.yticks()
plt.ylim(0,1,1)

plt.subplot(529)
# plot upper_lim of the room temperature
plt.plot(time_900, Tupper, 'k--', lw=0.5, label='Bounds')
# plot lower_limit of the room temperature
plt.plot(time_900, Tlower, 'k--', lw=0.5)
plt.plot(time_900, results_900['conVAVWes.TZon']-273.15, 'b-',label='Measurement')
plt.plot(t_opt, TWes_pred, 'b:',label='Prediction')
plt.ylabel('West Zone', )
plt.xlabel('Time')
plt.xticks(time_xticks,time_xticklabels)
plt.yticks()

plt.subplot(5,2,10)
plt.plot(time_900, results_900['VSupWes_flow.V_flow'], 'b-', label='Measured')
plt.plot(time_900, results_900['conVAVWes.damVal.VDisSet_flow'], 'b:', label='Setpoint')
plt.xlabel('Time')
plt.xticks(time_xticks, time_xticklabels)
plt.yticks()
plt.ylim(0,1,1)

plt.savefig('./results/zone_temp_flowrate_PH'+str(PH)+'.png')
#plt.show()

# define metric function
price_tou = [0.0640, 0.0640, 0.0640, 0.0640,
             0.0640, 0.0640, 0.0640, 0.0640,
             0.1391, 0.1391, 0.1391, 0.1391,
             0.3548, 0.3548, 0.3548, 0.3548,
             0.3548, 0.3548, 0.1391, 0.1391,
             0.1391, 0.1391, 0.1391, 0.0640]
def get_metrics(Ptot,TZone,price_tou,nsteps_h=4):
    """
    TZone: ixk - k is the number of zones
    """
    n= len(Ptot)
    energy_cost = []
    temp_violation = []

    for i in range(n):
        # assume 1 step is 15 minutes and data starts from hour 0
        hindex = (i%(nsteps_h*24))//nsteps_h

        # energy cost
        power=Ptot[i]
        price = price_tou[hindex]
        energy_cost.append(power/1000./nsteps_h*price)

        # maximum temperature violation
        number_zone = 5

        T_upper = np.array([30.0 for j in range(24)])
        T_upper[6:19] = 25.0
        T_lower = np.array([12.0 for j in range(24)])
        T_lower[6:19] = 20.0

        overshoot = []
        undershoot = []
        violation = []
        for k in range(number_zone):
            overshoot.append(np.array([float((TZone[i,k] -273.15) - T_upper[hindex]), 0.0]).max())
            undershoot.append(np.array([float(T_lower[hindex] - (TZone[i,k]-273.15)), 0.0]).max())
            violation.append(overshoot[k]+undershoot[k])
        temp_violation.append(violation)
    print(np.array(energy_cost).shape)
    print(np.array(temp_violation).shape)
    return np.concatenate((np.array(energy_cost).reshape(-1,1), np.array(temp_violation)),axis=1)


PTot = results_900[['chi.P',
                     'priPum.P',
                     'secPum.P',
                     'fanSup.P']].sum(axis=1)
TZones = results_900[['conVAVCor.TZon',
                     'conVAVSou.TZon',
                     'conVAVEas.TZon',
                     'conVAVNor.TZon',
                     'conVAVWes.TZon']].values
nsteps_hour = int(3600./900)
metrics = get_metrics(PTot.values, TZones, price_tou, nsteps_hour)
metrics = pd.DataFrame(metrics, columns=[['energy_cost', 'temp_violation1',
                       'temp_violation2', 'temp_violation3', 'temp_violation4', 'temp_violation5']])
# save for future comparison
mpc_results_metrics = {'energy': float(PTot.sum()/nsteps_hour/1000),
                        'energy_cost': float(metrics[["energy_cost"]].sum()),
                        'max_temp_violation': float(metrics[['temp_violation1',
                                                           'temp_violation2', 
                                                           'temp_violation3', 
                                                           'temp_violation4', 
                                                           'temp_violation5']].max().max()),
                        'total_temp_violation': float(metrics[['temp_violation1',
                                                             'temp_violation2',
                                                             'temp_violation3',
                                                             'temp_violation4',
                                                             'temp_violation5']].sum().sum()/nsteps_hour),
                        'core_Zone_temp_violation': float(metrics[['temp_violation1']].sum()/nsteps_hour),
                        'east_Zone_temp_violation': float(metrics[['temp_violation2']].sum()/nsteps_hour),
                        'north_Zone_temp_violation': float(metrics[['temp_violation3']].sum()/nsteps_hour),
                        'south_Zone_temp_violation': float(metrics[['temp_violation4']].sum()/nsteps_hour),
                        'west_Zone_temp_violation': float(metrics[['temp_violation5']].sum()/nsteps_hour)}

with open('./results/mpc_performance_metrics_PH'+str(PH)+'.json', 'w') as outfile:
    json.dump(mpc_results_metrics, outfile)
